In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import geopandas as gpd
from skimpy import clean_columns
import requests

## Fire Hydrants Locations accorss LA County

In [2]:
# read in LACoFD station locations
hydrants = gpd.read_file("../data/Fire_Hydrants_(DWP).geojson")
hydrants.head()

,OBJECTID,HYDRTS_ID,SIZE_CODE,MAKE_CODE,MAKE_DESCRIPTION,MAIN_SIZE,TOOLTIP,NLA_URL,geometry
0,1,7726.0,2 1/2 X 4D,CLOW,Clow,6.0,Size: 2 1/2 X 4D\nType: Clow\nMain Size: 6,navigatela/reports/fire_hydrants_dwp.cfm?PK=7726,POINT (-118.28914 33.98814)
1,2,82228.0,2 1/2 X 4D,CLOW,Clow,12.0,Size: 2 1/2 X 4D\nType: Clow\nMain Size: 12,navigatela/reports/fire_hydrants_dwp.cfm?PK=82228,POINT (-118.17835 34.08972)
2,3,10859.0,2 1/2 X 4D,JONES,Jones,6.0,Size: 2 1/2 X 4D\nType: Jones\nMain Size: 6,navigatela/reports/fire_hydrants_dwp.cfm?PK=10859,POINT (-118.27587 34.08153)
3,4,11722.0,2 1/2 X 4D,CLOW,Clow,6.0,Size: 2 1/2 X 4D\nType: Clow\nMain Size: 6,navigatela/reports/fire_hydrants_dwp.cfm?PK=11722,POINT (-118.17871 34.08793)
4,5,14647.0,2 1/2 X 4D,CLOW,Clow,6.0,Size: 2 1/2 X 4D\nType: Clow\nMain Size: 6,navigatela/reports/fire_hydrants_dwp.cfm?PK=14647,POINT (-118.27183 33.94364)

In [3]:
hydrants = hydrants[["OBJECTID", "HYDRTS_ID", "geometry"]].copy()
hydrants = hydrants.rename(columns={"OBJECTID": "objectid", "HYDRTS_ID": "hydrantid"})
hydrants.head()

   objectid  hydrantid                     geometry
0         1     7726.0  POINT (-118.28914 33.98814)
1         2    82228.0  POINT (-118.17835 34.08972)
2         3    10859.0  POINT (-118.27587 34.08153)
3         4    11722.0  POINT (-118.17871 34.08793)
4         5    14647.0  POINT (-118.27183 33.94364)

In [4]:
# save dataframe
hydrants.to_file('../data/Fire_Hydrants.geojson')