In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import geopandas as gpd
from skimpy import clean_columns
import requests

## LA County Hospital and Medical Centers Locations

In [2]:
# read in Hospital locations
hospital_df = gpd.read_file("../data/Hospitals_and_Medical_Centers.geojson")
hospital_df.head()

,OBJECTID,source,ext_id,cat1,cat2,cat3,org_name,Name,addrln1,addrln2,...,link,use_type,latitude,longitude,date_updated,email,dis_status,POINT_X,POINT_Y,geometry
0,9,211,NaN,Health and Mental Health,Hospitals and Medical Centers,911 Receiving,,Verdugo Hills Hospital,1812 Verdugo Blvd.,NaN,...,http://egis3.lacounty.gov/lms/?p=560,publish,34.204530,-118.216023,2016-01-29 10:45:00+00:00,NaN,None,6.496353e+06,1.896883e+06,POINT (-118.21602 34.20453)
1,11,211,NaN,Health and Mental Health,Hospitals and Medical Centers,Respiratory Hospital,,Barlow Respiratory Hospital - Los Angeles (Mai...,2000 Stadium Way,NaN,...,http://egis3.lacounty.gov/lms/?p=561,publish,34.075693,-118.248312,2016-01-21 15:56:47+00:00,NaN,None,6.486475e+06,1.850019e+06,POINT (-118.24831 34.07569)
2,20,211,NaN,Health and Mental Health,Hospitals and Medical Centers,911 Receiving,,Glendora Community Hospital,150 W. Route 66,NaN,...,http://egis3.lacounty.gov/lms/?p=568,publish,34.127307,-117.865075,2016-01-22 14:39:39+00:00,NaN,None,6.602504e+06,1.868737e+06,POINT (-117.86507 34.12731)
3,25,211,NaN,Health and Mental Health,Hospitals and Medical Centers,911 Receiving,Providence Little Company of Mary Medical Center,Providence Little Company Of Mary Medical Cent...,4101 Torrance Blvd.,NaN,...,http://egis3.lacounty.gov/lms/?p=569,publish,33.838634,-118.357113,2016-01-27 11:34:40+00:00,NaN,None,6.453221e+06,1.763848e+06,POINT (-118.35711 33.83863)
4,35,211,NaN,Health and Mental Health,Hospitals and Medical Centers,911 Receiving,,Glendale Memorial Hospital And Health Center,1420 S. Central Ave.,NaN,...,http://egis3.lacounty.gov/lms/?p=570,publish,34.128058,-118.257443,2016-01-22 16:10:02+00:00,NaN,None,6.483758e+06,1.869083e+06,POINT (-118.25744 34.12806)

In [3]:
hospital_df = hospital_df[["OBJECTID", "Name", "city", "geometry"]].copy()
hospital_df = hospital_df.rename(columns={"OBJECTID": "objectid", "Name": "name"})
hospital_df.head()

,objectid,name,city,geometry
0,9,Verdugo Hills Hospital,Glendale,POINT (-118.21602 34.20453)
1,11,Barlow Respiratory Hospital - Los Angeles (Mai...,Los Angeles,POINT (-118.24831 34.07569)
2,20,Glendora Community Hospital,Glendora,POINT (-117.86507 34.12731)
3,25,Providence Little Company Of Mary Medical Cent...,Torrance,POINT (-118.35711 33.83863)
4,35,Glendale Memorial Hospital And Health Center,Glendale,POINT (-118.25744 34.12806)

In [4]:
hospital_df.to_file('../data/hospitals.geojson')