In [1]:
import gudhi as gd
import geopandas as gpd
import numpy as np

In [6]:
hvi_df = gpd.read_file("../data/CHAT-Los Angeles County-vulnerability-indicators.csv")
hvi_df.head()

,census_tract,census_county,census_city,heat_health_action_index,perc_children,perc_no_hs_diploma,perc_elderly,perc_outdoor_workers,tract_population,perc_poverty,...,perc_low_birth_weight,cardio_disease_prevalence,perc_ambulatory_disability,perc_cognitive_disability,pm25_concentration,perc_impervious_surfaces,change_in_dev,perc_no_tree_canopy,uhii_avgdeltat,ozone_exceedance
0,6037101110,Los Angeles County,Tujunga,36.53,4.90,19.70,13.40,6.57,4824,14.50,...,3.44,10.81,7.40,5.00,11.04,43.11,0.00,94.14,2.26,0.19
1,6037101122,Los Angeles County,Tujunga,19.76,1.70,4.70,15.50,7.68,3291,2.70,...,5.05,8.87,3.90,2.00,10.95,25.36,12.44,90.80,,0.19
2,6037101210,Los Angeles County,Tujunga,43.45,3.90,22.80,8.80,8.38,5882,24.00,...,4.89,10.81,8.20,5.20,11.11,56.99,0.00,95.99,,0.18
3,6037101220,Los Angeles County,Tujunga,40.68,4.70,17.80,11.80,4.80,2902,14.20,...,4.27,10.81,10.40,5.10,11.14,45.24,0.00,95.35,,0.18
4,6037101300,Los Angeles County,La Crescenta,23.03,2.50,10.10,20.20,8.01,4410,7.30,...,3.48,8.16,7.40,2.90,11.19,36.00,25.15,92.52,,0.17

In [7]:
hvi_df = hvi_df[["census_tract", "census_county", "heat_health_action_index"]].copy()
hvi_df = hvi_df.rename(columns={"heat_health_action_index": "hvi"})
hvi_df.head()

  census_tract       census_county    hvi
0   6037101110  Los Angeles County  36.53
1   6037101122  Los Angeles County  19.76
2   6037101210  Los Angeles County  43.45
3   6037101220  Los Angeles County  40.68
4   6037101300  Los Angeles County  23.03

In [11]:
hvi_df.to_csv("../data/HVI_LACounty.csv", index=False)